### ISSUE TITLE
Error: Version doesn´t exist in botfile.js

### ISSUE THREAD

**Issue by iclaude3000** [npm/npm-lifecycle#24]
Hello, 

I am new to botpress, I am trying to follow the steps to run 

> npm start <

 following instructions from https://botpress.io/docs/latest/getting_started/trivia_template/

using:
npm v6.3.0
node v8.11.3

Error: Version doesn´t exist in botfile.js

Log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\claude.chelene\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.3.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tutorial@1.0.0~prestart: tutorial@1.0.0
6 info lifecycle tutorial@1.0.0~start: tutorial@1.0.0
7 verbose lifecycle tutorial@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle tutorial@1.0.0~start: PATH: C:\Users\claude.chelene\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\claude.chelene\Tutorial\step-1\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\CVArchiverAddin;C:\Program Files\Java\jre6\bin;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Users\claude.chelene\AppData\Roaming\npm
9 verbose lifecycle tutorial@1.0.0~start: CWD: C:\Users\claude.chelene\Tutorial\step-1
10 silly lifecycle tutorial@1.0.0~start: Args: [ '/d /s /c', 'botpress start' ]
11 silly lifecycle tutorial@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle tutorial@1.0.0~start: Failed to exec start script
13 verbose stack Error: tutorial@1.0.0 start: `botpress start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\claude.chelene\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\claude.chelene\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid tutorial@1.0.0
15 verbose cwd C:\Users\claude.chelene\Tutorial\step-1
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\claude.chelene\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.3
19 verbose npm  v6.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error tutorial@1.0.0 start: `botpress start`
22 error Exit status 1
23 error Failed at the tutorial@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ljharb** [comment]
That error doesn’t come from npm; it comes from botpress. You should file it there.
