### ISSUE TITLE
Tar package vulnerability on install

### ISSUE THREAD

**Issue by laurenfrederick** [npm/npm-lifecycle#28]
`npm-lifeycycle` is using a version of `node-gyp` which is pointing to a version of `tar` that has a vulnerability. See https://www.npmjs.com/advisories/803.

**Comment by evocateur** [comment]
The underlying issue has been [patched](https://github.com/nodejs/node-gyp/commit/1456ef27c72cc4e49f9b1d82cbb047cb673156c8) in the source of `node-gyp`. This issue isn't valid for `npm-lifecycle` (or `lerna`, for that matter).

**Comment by ChALkeR** [comment]
This can be resolved with either updating to a node-gyp@4 here or doing a patch release of  `npm/node-tar@2`, ref: https://github.com/npm/node-tar/issues/212.

**Comment by jhnferraris** [comment]
Created a PR to update node-gyp@4 here. https://github.com/npm/npm-lifecycle/pull/31

**Comment by kaiyoma** [comment]
When can we expect a release? lerna depends on this package, so all users of lerna are currently exposed to the tar vulnerability.
