### ISSUE TITLE
Node App crashes

### ISSUE THREAD

**Issue by x-504** [npm/npm-lifecycle#35]
Hi Guys my App is crashing randomly and this is the logs we are getting from the debug. I am not sure what could be . the cause of this. Any hint  you can provided?

https://pastebin.com/nEVRQ4Lv

**Comment by Renari** [comment]
I'm running into a similar issue:

```
start: `cross-env NODE_ENV=production node .build/main.js`
13 verbose stack Exit status 126
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by isaacs** [comment]
It looks like the `node server` command exited in error.  Does it work when you run `node server`?

**Comment by kikemx78** [comment]
Same issue here. Happening only on production. 

`13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/hostaccount/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/hostaccount/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)`

**Comment by Renari** [comment]
For me I uninstalled cross-env which removed the dependency on npm-lifecycle and I was able to run `node .build/main.js` after that.
