### ISSUE TITLE
Should node-gyp be dependency of npm-lifecycle?

### ISSUE THREAD

**Issue by zkochan** [npm/npm-lifecycle#4]
Currently `npm-lifecycle` relies on the [node-gyp-bin](https://github.com/npm/npm/tree/latest/bin/node-gyp-bin) folder of npm (https://github.com/npm/lifecycle/blob/latest/index.js#L94). This makes npm-lifecycle not too usable outside of npm itself.

I think `node-gyp-bin` should be moved to `npm-lifecycle` and `node-gyp` should be in dependencies of `npm-lifecycle`.

**Comment by zkochan** [comment]
Seems like the bins in `node-gyp-bin` should know the locations of node-gyp though, which is problematic with flat node_modules. Alternatively, maybe npm-lifecycle has to have an option to get a custom node-gyp path location.

**Comment by iarna** [comment]
I can see no reason that `npm-lifecycle` shouldn't be the thing bundling `node-gyp`.
